name: schedule_run
on:
  workflow_dispatch:
  schedule:
    - cron: 15 16 * * 1-5
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull collection files
        uses: actions/checkout@v4
      - name: install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run postman collection
        run: 'newman run collection.json -e environment.json --reporters cli,htmlextra --reporter-htmlextra-export report.html'
      - name: publish report
      - uses: actions/upload-artifact@v3
        with:
         name: Reports
         path: "*html"
